title: Aurora Free Open Source Software
email: contact@aurorafoss.org
description: Aurora Free Software Collection

twitter: aurorafossorg
facebook: aurorafossorg
gitlab: aurorafossorg
github: aurorafossorg
discord_url: https://discord.gg/Tsb2gpk

markdown: kramdown

url: "https://www.aurorafoss.org"

theme: fuzzy-theme

exclude: [vendor, "Gemfile", "Gemfile.lock", ".gitlab-ci.yml", "build"]
